import type { Collection } from 'mongodb'
import type { ArcanumLeaf } from './types.js'
import { poseidon, computeLeaf } from './poseidon.js'

// =============================================================================
// ArcanumTree — append-only Poseidon Merkle tree for anonymous note commitments
// =============================================================================
//
// TREE DESIGN — chosen once, never changed:
//
//   Type:   Binary Incremental Merkle Tree (IMT)
//   Depth:  32  — 2^32 = 4.3 billion notes. You will never outgrow this.
//   Arity:  2   — standard binary, matches circomlib MerkleProof template
//   Hash:   Poseidon — ZK-friendly, matches the circuit
//
//   ZERO_LEAF = poseidon(0)   — empty leaf sentinel
//   zero[L]   = poseidon(zero[L-1], zero[L-1])  — empty subtree at level L
//
// WHY DEPTH 32:
//   Any smaller depth creates a migration problem. Migration means:
//   1. New circuit + new tree
//   2. Old proofs reference old root — instantly invalid
//   3. Anonymity set resets to zero
//
//   Depth 32 is the library maximum. 4.3B notes at ~1 note/user/month =
//   430 years at 10M users. This tree will never fill.
//
// STORAGE (MongoArcanumTree):
//   - Leaf records persisted to MongoDB: { leafIndex, commitment, leaf, valor }
//   - On startup: load all leaves in insertion order, rebuild in-memory tree
//   - In-memory tree used for all get/proof operations — O(1) reads
//   - After insert: persist leaf, update in-memory tree — O(depth) writes
//   - Correct for up to ~10M leaves without architectural change
//   - Beyond that: switch to incremental node-level storage (future work)
//
// ANONYMITY SET:
//   All notes ever issued share one anonymity set — the single tree.
//   Never split. Never reset. The set only grows.
// =============================================================================

export const TREE_DEPTH = 32

// Precomputed zero values: zero[L] = poseidon(zero[L-1], zero[L-1])
// zero[0] = poseidon(0n) — the canonical empty leaf
// Generated by: node -e "... poseidon chain ..."
// Must match the circuit's implicit zero values.
export const ZERO_VALUES: readonly string[] = Object.freeze([
  '19014214495641488759237505126948346942972912379615652741039992445865937985820', // zero[0] = poseidon(0)
  '10447686833432518214645507207530993719569269870494442919228205482093666444588', // zero[1]
  '2186774891605521484511138647132707263205739024356090574223746683689524510919',  // zero[2]
  '6624528458765032300068640025753348171674863396263322163275160878496476761795',  // zero[3]
  '17621094343163687115133447910975434564869602694443155644084608475290066932181', // zero[4]
  // Levels 5–32 computed lazily on first use (see getZeroValue)
])

const _computedZeros: string[] = [...ZERO_VALUES]

async function getZeroValue(level: number): Promise<string> {
  if (_computedZeros[level] !== undefined) return _computedZeros[level]
  const prev = await getZeroValue(level - 1)
  const z = await poseidon([BigInt(prev), BigInt(prev)])
  _computedZeros[level] = z
  return z
}

/** Merkle proof as used by the snarkjs circuit. */
export interface ArcanumMerkleProof {
  root: string
  leafIndex: number
  pathElements: string[]   // sibling hashes, length = TREE_DEPTH
  pathIndices: number[]    // 0 = sibling is on the right, 1 = sibling is on the left
}

/**
 * ArcanumTreeStore — the anonymous side of the ledger.
 * No animaId ever touches these records.
 */
export interface ArcanumTreeStore {
  insert(commitment: string, valor: bigint): Promise<{ leafIndex: number; proof: ArcanumMerkleProof }>
  getProof(leafIndex: number): Promise<ArcanumMerkleProof>
  getRoot(): Promise<string>
  findLeaf(commitment: string): Promise<ArcanumLeaf | null>
  size(): Promise<number>
}

// ---------------------------------------------------------------------------
// MemoryArcanumTree — correct for tests and small deployments
// ---------------------------------------------------------------------------

export class MemoryArcanumTree implements ArcanumTreeStore {
  // Full tree stored as nodes[level][index] = hash
  // Missing entries are zero values (computed lazily)
  private readonly nodes: Map<number, Map<bigint, string>> = new Map()
  private readonly leaves: ArcanumLeaf[] = []
  private readonly commitmentIndex = new Map<string, number>()
  private _root: string | null = null
  private _initialized = false

  private async ensureInit() {
    if (this._initialized) return
    this._root = await getZeroValue(TREE_DEPTH)
    this._initialized = true
  }

  private async getNode(level: number, index: bigint): Promise<string> {
    return this.nodes.get(level)?.get(index) ?? await getZeroValue(level)
  }

  private setNode(level: number, index: bigint, value: string) {
    if (!this.nodes.has(level)) this.nodes.set(level, new Map())
    this.nodes.get(level)!.set(index, value)
  }

  async insert(commitment: string, valor: bigint): Promise<{ leafIndex: number; proof: ArcanumMerkleProof }> {
    await this.ensureInit()
    const leafIndex = this.leaves.length
    const leaf = await computeLeaf(commitment, valor)

    // Walk up the tree updating the path
    let current = leaf
    let currentIndex = BigInt(leafIndex)
    for (let level = 0; level < TREE_DEPTH; level++) {
      this.setNode(level, currentIndex, current)
      const sibling = await this.getNode(level, currentIndex ^ 1n)
      const isLeft = currentIndex % 2n === 0n
      current = await poseidon(isLeft ? [BigInt(current), BigInt(sibling)] : [BigInt(sibling), BigInt(current)])
      currentIndex = currentIndex >> 1n
    }
    this._root = current

    const record: ArcanumLeaf = { commitment, leaf, valor, leafIndex, insertedAt: new Date() }
    this.leaves.push(record)
    this.commitmentIndex.set(commitment, leafIndex)

    const proof = await this.getProof(leafIndex)
    return { leafIndex, proof }
  }

  async getProof(leafIndex: number): Promise<ArcanumMerkleProof> {
    await this.ensureInit()
    if (leafIndex >= this.leaves.length) {
      throw new Error(`Leaf index ${leafIndex} out of range (tree has ${this.leaves.length} leaves)`)
    }
    const pathElements: string[] = []
    const pathIndices: number[] = []
    let currentIndex = BigInt(leafIndex)
    for (let level = 0; level < TREE_DEPTH; level++) {
      const siblingIndex = currentIndex ^ 1n
      pathElements.push(await this.getNode(level, siblingIndex))
      pathIndices.push(Number(currentIndex % 2n))   // 0 = we're left child, 1 = we're right child
      currentIndex = currentIndex >> 1n
    }
    return { root: this._root!, leafIndex, pathElements, pathIndices }
  }

  async getRoot(): Promise<string> {
    await this.ensureInit()
    return this._root!
  }

  async findLeaf(commitment: string): Promise<ArcanumLeaf | null> {
    const idx = this.commitmentIndex.get(commitment)
    return idx !== undefined ? (this.leaves[idx] ?? null) : null
  }

  async size(): Promise<number> {
    return this.leaves.length
  }
}

// ---------------------------------------------------------------------------
// MongoArcanumTree — production tree backed by MongoDB
// ---------------------------------------------------------------------------
//
// Strategy: persist leaf records to MongoDB; maintain an in-memory
// MemoryArcanumTree for all operations. On startup, load leaves in order
// and rebuild the in-memory tree.
//
// Correct for up to ~10M leaves. Beyond that, switch to persisting all
// (level, index) nodes directly (incremental node-level storage).
// ---------------------------------------------------------------------------

type LeafDoc = {
  leafIndex: number
  commitment: string
  leaf: string
  valor: string   // bigint serialized as decimal string
  insertedAt: Date
}

export class MongoArcanumTree implements ArcanumTreeStore {
  private mem: MemoryArcanumTree = new MemoryArcanumTree()
  private loaded = false

  constructor(private readonly col: Collection) {}

  private async load(): Promise<void> {
    if (this.loaded) return
    const docs = await this.col
      .find({})
      .sort({ leafIndex: 1 })
      .toArray() as unknown as LeafDoc[]

    // Rebuild in-memory tree from persisted leaves
    for (const doc of docs) {
      await this.mem.insert(doc.commitment, BigInt(doc.valor))
    }
    this.loaded = true
  }

  async insert(commitment: string, valor: bigint): Promise<{ leafIndex: number; proof: ArcanumMerkleProof }> {
    await this.load()
    const { leafIndex, proof } = await this.mem.insert(commitment, valor)
    const leaf = await computeLeaf(commitment, valor)
    const doc: LeafDoc = {
      leafIndex,
      commitment,
      leaf,
      valor: valor.toString(),
      insertedAt: new Date(),
    }
    await this.col.insertOne(doc)
    return { leafIndex, proof }
  }

  async getProof(leafIndex: number): Promise<ArcanumMerkleProof> {
    await this.load()
    return this.mem.getProof(leafIndex)
  }

  async getRoot(): Promise<string> {
    await this.load()
    return this.mem.getRoot()
  }

  async findLeaf(commitment: string): Promise<ArcanumLeaf | null> {
    await this.load()
    return this.mem.findLeaf(commitment)
  }

  async size(): Promise<number> {
    await this.load()
    return this.mem.size()
  }
}
