const defaultUserData = {
    userId: '',
    wallet: '',
    balance: '',
    verified: false,
    exp: 0,
    points: 0,
    doints: 0,
    qoints: 0,
    boints: 0,
    pendingQoints: 0,
    input_batch: 1,
    input_steps: 30,
    input_cfg: 7,
    input_strength: .6,
    input_image: '',
    input_height: 1024,
    input_width: 1024,
    prompt: '',
    userPrompt: '-1',
    basePrompt: "MS2",
    input_negative: '-1',
    input_checkpoint: "zavychromaxl_v60",
    input_seed: -1,
    lastSeed: -1,
    advancedUser: false,
    lastImage: '',
    tempSize: {
        height: 500,
        width: 500
    },
    state: {
        state: 'IDLE',
        chatId: null,
        messageThreadId: null
    },
    type: '',
    voiceModel: "165UvtZp7kKnmrVrVQwx",
    waterMark: 'mslogo',
    inpaintTarget: '',
    controlNet: false,
    styleTransfer: false,
    openPose: false,
    createSwitch: 'SDXL',
    loras: [],
    collections: [],
    groups: [],
    runs: [],
    commandList:  [
        { command: 'help', description: 'See help description' },
        { command: 'make', description: 'SDXL txt2img'},
        { command: 'signin', description: 'Connect account' },
        { command: 'ca', description: 'Check chart buy' },
        { command: 'loralist', description: 'See available LoRAs' },
        { command: 'status', description: 'Check the group queue status' },
    ],
    favorites: {
        basePrompt: [],
        gens: [],
        loras: [],
    },
    kickedAt: '',
    lastRunTime: '',
};

module.exports = defaultUserData